config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'session#new', as: 'login'
  get 'logout', to: 'session#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'home/index'

  resources :session, only: [:new, :create, :destroy]
  resources :posts
  resources :users do
    get :confirmation_email, on: :member
  end

  root 'home#index'
end

app/models/access_profile.rb
class AccessProfile < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 255 }
  validates :is_admin, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
 class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, email_format: true, uniqueness: true
  validates :password, confirmation: true, length: { minimum: 6 }

  before_create {generate_token(:confirmation_token)}
  before_create {generate_token(:auth_token)}

  def email_activate
    self.confirmation_token = nil
    save!(:validate => false)
  end

  def full_name
    "#{self.name} - #{self.last_name}"
  end

  private

  def generate_token(column)
    loop do
      self[column] = SecureRandom.urlsafe_base64
      break unless User.exists?(column => self[column])
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, except: [:show]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user_id = current_user.id
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :tags)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email]) || User.find_by(login: params[:email])
    if user && user.authenticate(params[:password])
      if user.confirmation_token.blank? || user.confirmation_token.nil?

        if params[:remember_me] == 1
          cookies.permanent[:auth_token] = user.auth_token
          cookies.signed[:user_id] = user.id
        else
          session[:user_id] = user.id
        end

        flash[:success] = t('session.controller.logged_in', name: user.name)
        redirect_to root_url
      else
        flash.now[:danger] = t('session.controller.not_confirmed')
        render :new
      end
    else
      flash[:danger] = t('session.controller.wrong_password')
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    cookies.delete(:auth_token) if cookies[:auth_token].present?
    cookies.delete(:user_id) if cookies.signed[:user_id].present?

    flash[:success] = t('session.controller.logged_out')
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:index, :edit, :update, :destroy]

  def confirmation_email
    user = User.find_by(confirmation_token: params[:id])
    if user
      user.email_activate
      flash[:success] = t('user.controller.confirmation_success')
      redirect_to login_url
    else
      flash[:danger] = t('user.controller.confirmation_fail')
      redirect_to root_url
    end
  end

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.confirmation_email(@user).deliver_now
      flash[:success] = t('user.controller.success', email: @user.email)
      redirect_to root_url
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_container_div(&block)
    content = block_given? ? capture(&block) : ''.html_safe
    div_class = "container #{action_name}-#{controller_name}-container"
    content_tag(:div, content, class: div_class, id: "body_container")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    if cookies[:auth_token].present? || session[:user_id].present?
      User.find_by(id: cookies.signed[:user_id]) || User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    unless current_user.present?
      redirect_to root_url
      flash[:warning] = t('session.controller.not_logged')
    end
  end

  def is_admin?
    unless logged_in? && current_user.is_admin
      redirect_to root_url
      flash[:warning] = t('session.controller.not_admin')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="masthead">
  <div class="row">
    <div class="col-md-7">
      <h1>Blog
        <p class="lead">Catchy Subtitle Here</p>
      </h1>
    </div>
    <div class="col-md-5">
      <div class="well well-lg">
        <div class="row">
          <div class="col-sm-12">
            Ad Space
          </div>
        </div>
      </div>
    </div>
  </div><!-- /cont -->

</div>
<%#= console %>

<div class="container">
  <div class="row">

    <div class="col-md-12">

      <div class="panel">
        <div class="panel-body">


          <!--/stories-->
		  <div class="row">
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="//placehold.it/100" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3>Post Entry Title</h3>
              <div class="row">
                <div class="col-xs-9">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                  Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
                  dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
                  Aliquam in felis sit amet augue.</p>
                  <p class="lead"><button class="btn btn-default">Read More</button></p>
                  <p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
                  <ul class="list-inline"><li><a href="#">2 Days Ago</a></li><li><a href="#"><i class="glyphicon glyphicon-comment"></i> 4 Comments</a></li><li><a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

		  <div class="row">
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="//placehold.it/100" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3>Story Title Here</h3>
              <div class="row">
                <div class="col-xs-9">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                  Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
                  dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
                  Aliquam in felis sit amet augue.</p>
                  <p class="lead"><button class="btn btn-default">Read More</button></p>
                  <p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
                  <ul class="list-inline"><li><a href="#">3 Days Ago</a></li><li><a href="#"><i class="glyphicon glyphicon-comment"></i> 1 Comments</a></li><li><a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

          <div class="row">
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="//placehold.it/100" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3>Post Heading Here</h3>
              <div class="row">
                <div class="col-xs-9">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                  Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
                  dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
                  Aliquam in felis sit amet augue.</p>
                  <p class="lead"><button class="btn btn-default">Read More</button></p>
                  <p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
                  <ul class="list-inline"><li><a href="#">5 Days Ago</a></li><li><a href="#"><i class="glyphicon glyphicon-comment"></i> 0 Comments</a></li><li><a href="#"><i class="glyphicon glyphicon-share"></i> 45 Shares</a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

          <div class="row">
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="//placehold.it/100" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3>Another Entry Title</h3>
              <div class="row">
                <div class="col-xs-9">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                  Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
                  dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
                  Aliquam in felis sit amet augue.</p>
                  <p class="lead"><button class="btn btn-default">Read More</button></p>
                  <p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
                  <ul class="list-inline"><li><a href="#">1 Week Ago</a></li><li><a href="#"><i class="glyphicon glyphicon-comment"></i> 4 Comments</a></li><li><a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>
          <!--/stories-->


          <a href="/" class="btn btn-primary pull-right btnNext">More <i class="glyphicon glyphicon-chevron-right"></i></a>


        </div>
      </div>



   	</div><!--/col-12-->
  </div>
</div>


<hr>
</div>

<div class="container" id="footer">
  <div class="row">
    <div class="col col-sm-12">

      <h1>Follow Us</h1>
      <div class="btn-group">
       <a class="btn btn-twitter btn-lg" href="#"><i class="icon-twitter icon-large"></i> Twitter</a>
	   <a class="btn btn-facebook btn-lg" href="#"><i class="icon-facebook icon-large"></i> Facebook</a>
	   <a class="btn btn-google-plus btn-lg" href="#"><i class="icon-google-plus icon-large"></i> Google+</a>
      </div>

    </div>
  </div>
</div>

<hr>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-inline">
          <li><i class="icon-facebook icon-2x"></i></li>
          <li><i class="icon-twitter icon-2x"></i></li>
          <li><i class="icon-google-plus icon-2x"></i></li>
          <li><i class="icon-pinterest icon-2x"></i></li>
        </ul>

      </div>
      <div class="col-sm-6">
          <p class="pull-right">Built with <i class="icon-heart-empty"></i> at <a href="http://www.bootply.com">Bootply</a></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baú Gospel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Home", root_path, class: 'navbar-brand') %>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to(t('navbar.signup'), new_user_path) %>
        </li>
        <li>
          <%= link_to(t('actioncontroller.session.login'), login_path) %>
        </li>
        <li>
          <a href="#">Category</a>
        </li>
        <li>
          <a href="#">Category</a>
        </li>
      </ul>
      <ul class="nav navbar-right navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-search"></i></a>
          <ul class="dropdown-menu" style="padding:12px;">
            <form class="form-inline">
            	<div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Go!</button>
                  </span>
            	</div>
            </form>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>
  <%= body_container_div do %>

    <div class='flash-messages col-sm-12 col-md-12 col-lg-12'>
      <% flash.each do |key, value| %>
        <div class="alert alert-dismissible alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  <% end %>
</body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
  <%= f.text_field :title, label: t('post.view.new.title') %>
  <%= f.text_area :body, label: t('post.view.new.body') %>
  <%= f.hidden_field :user_id %>
  <%= f.text_field :tags, label: t('post.view.new.tags') %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.user %></td>
        <td><%= post.tags %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tags %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/session/new.html.erb
<div class="container">
    <div class="row vertical-offset-100">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= t('actioncontroller.session.title') %></h3>
        </div>
          <div class="panel-body">
            <%= bootstrap_form_tag url: session_index_path do |f| %>
              <%= f.text_field :email, label: t('session.view.email') %>
              <%= f.password_field :password, label: t('session.view.password') %>

              <%= f.form_group :remember_me do %>
                <%= f.check_box :remember_me, label: t('session.view.remember_me') %>
              <% end %>

              <%= f.submit t('session.view.submit'), class: 'btn btn-success' %>
              <%= link_to t('session.view.signup'), signup_path, class: 'btn btn-default' %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :email, label: t('user.view.new.email') %>
  <%= f.text_field :login, label: t('user.view.new.login') %>
  <%= f.text_field :name, label: t('user.view.new.name') %>
  <%= f.text_field :last_name, label: t('user.view.new.last_name') %>
  <%= f.password_field :password, label: t('user.view.new.password') %>
  <%= f.password_field :password_confirmation, label: t('user.view.new.password_confirmation') %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="contaier_new_user">
  <h1>New User</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>